config/routes.rb
Demo03::Application.routes.draw do

  apipie

  resources :admin, :only => [:index], :controller => :admin do
    collection do

    end
  end
  namespace :admin do
    resources :employees
    resources :admin_users
  end

  devise_for :users

  resource :home, :controller => :home do

  end

  root :to => "home#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  attr_accessible :user_id, :status

  belongs_to :user
end

app/models/employee.rb
class Employee < ActiveRecord::Base


  ROLES = ["manager", "hr"]

  attr_accessible :user_id, :code, :surname, :first_name, :last_name, :birth_date, :join_date, :contact_mobile, :picture,
                  :designation, :role,
                  :user_attributes

  validates_presence_of :code, :surname, :first_name, :last_name, :birth_date, :join_date, :contact_mobile
  validates :code,
            :uniqueness => true,
            :format => {:with => /\A[a-zA-Z0-9]+\z/,
                        :message => "Only letters and numbers are allowed"}
  validates_date :birth_date, :on_or_before => lambda { Date.current }
  validates_date :join_date, :on_or_before => lambda { Date.current }
  validates_date :join_date, :after => :birth_date
  validates :contact_mobile,
            :numericality => {:only_integer => true},
            :format => {:with => /^[0-9]{10,11}$/}

  belongs_to :user, :dependent => :destroy


  accepts_nested_attributes_for :user

  has_attached_file :picture,
                    :styles => {
                      :medium => "140x140",
                      :thumb => "100x100"
                    },
                    :default_url => "/assets/default_picture_:style.png",
                    :path => ":rails_root/public/uploads/:class/:attachment/:id/:basename_:style.:extension",
                    :url => "/uploads/:class/:attachment/:id/:basename_:style.:extension"


  scope :default, includes(:user)

  def display_code
    code.try(:upcase)
  end

  def name
    "#{first_name} #{last_name}".titleize
  end

  def full_name
    "#{surname} #{first_name} #{last_name}".titleize
  end

  def email
    user.email
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :admin_user, :dependent => :destroy
  has_one :employee, :dependent => :destroy

  scope :default, includes(:employee)
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < AdminController

  def index
    @admin_user = AdminUser.new
    @admin_users = AdminUser.includes(:user)
  end

  def create
    @user = User.find_by_email params[:email]
    if @user
      @user.build_admin_user
      @user.save
      flash[:notice] = "#{@user.email} is successfully added as admin."
    else
      flash[:error] = "Error while adding as admin. Please enter valid email."
    end
    redirect_to admin_admin_users_path
  end

  def destroy
    admin_user = AdminUser.find params[:id]
    if admin_user == current_user.admin_user
      flash[:error] = "You can't delete yourself form admin users"
    elsif AdminUser.count < 2
      flash[:error] = "Their should be One Admin User"
    else
      admin_user.destroy
      flash[:success] = "Admin User deleted successfully"
    end

    redirect_to admin_admin_users_path
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < AdminController

  def index
    @page = params[:page] || 1
    params[:per_page] ||= 10
    @employees = Employee.paginate(:page => @page, :per_page => params[:per_page]).order("first_name ASC")
  end

  def new
    @employee = Employee.new
    @employee.build_user
  end

  def create
    #setting default password as 123456
    params[:employee][:user_attributes][:password] = 123456
    params[:employee][:user_attributes][:password_confirmation] = 123456

    @employee = Employee.new(params[:employee])

    if @employee.save
      flash[:info] = "New employee is created!"
      redirect_to admin_employees_path
    else
      flash[:error] = "Errors while saving record!"
      render :new
    end
  end

  def show
    @employee = Employee.find params[:id]
  end

  def edit
    @employee = Employee.find params[:id]
  end

  def update
    @employee = Employee.find params[:id]

    if @employee.update_attributes(params[:employee])
      flash[:info] = "Employee is updated!"
      redirect_to admin_employees_path
    else
      flash[:error] = "Errors while saving record!"
      render :edit
    end
  end

  def destroy
    @employee = Employee.find params[:id]
    @employee.destroy
    flash[:info] = "Employee record is deleted!"
    redirect_to admin_employees_path
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  api :GET, '/users/:id'
  param :id, :number
  def index

  end

  private

  def authenticate_admin!
    unless current_user.admin_user
      flash[:notice] = "Access Denied, You are not Admin User!"
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/admin/admin_users_helper.rb
module Admin::AdminUsersHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admin_users/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for @admin_user, :url => admin_admin_users_path, :html => {:class => "form-inline", :role => "form"} do |f| %>
          <div class="form-group col-lg-4">
            <%= label_tag :email, "Email Address", :class => "sr-only" %>
            <%= text_field_tag :email, "", :class => "form-control", :placeholder => "Enter email" %>
          </div>
          <%= f.submit "Add as Admin", :class => "btn btn-default" %>
         <% end %>
      </div>
    </div>
  </div>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>#</th>
    <th>Email</th>
    <th>Name</th>
    <th style="width: 160px;">Options</th>
  </tr>
  </thead>
  <tbody>
  <% @admin_users.each.with_index do |admin_user, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= admin_user.user.email %></td>
      <td><%= admin_user.user.employee.name %></td>
      <td>
        <%= link_to admin_admin_user_path(admin_user), :class => "btn btn-danger btn-xs", :method => :delete, :confirm => "Are you sure?" do %>
          <span class="glyphicon glyphicon-trash"></span>
          Delete
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/employees/_form.html.erb
<%= form_for @employee, :url => (@employee.new_record? ? admin_employees_path : admin_employee_path(@employee)), :html => {:role => "role", :class => "form-horizontal"} do |f| %>
    <%= f.error_messages %>
    <%= f.fields_for :user do |u| %>
        <div class="form-group">
          <%= u.label :email, :class => "col-lg-2 control-label" %>
          <div class="col-lg-10">
            <%= u.text_field :email, :class => "form-control", :placeholder => "Email" %>
          </div>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :code, :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :code, :class => "form-control", :placeholder => "Code" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :surname, :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :surname, :class => "form-control", :placeholder => "Surname" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-6">
            <%= f.text_field :first_name, :class => "form-control", :placeholder => "First Name" %>
          </div>
          <div class="col-lg-6">
            <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last Name" %>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :designation, :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :designation, :class => "form-control", :placeholder => "Designation" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :role, :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select :role, options_for_select(Employee::ROLES.collect {|r| [r.humanize, r]}), {:include_blank => true}, {:class => "form-control"} %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :birth_date, 'Date of Birth', :class => "col-lg-4 control-label" %>
          <div class="col-lg-6">
            <%= f.text_field :birth_date, :class => "form-control", :placeholder => "YYYY-MM-DD" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :join_date, 'Date of Join', :class => "col-lg-4 control-label" %>
          <div class="col-lg-6">
            <%= f.text_field :join_date, :class => "form-control", :placeholder => "YYYY-MM-DD" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :contact_mobile, :class => "col-lg-4 control-label" %>
          <div class="col-lg-6">
            <%= f.text_field :contact_mobile, :class => "form-control", :placeholder => "Contact Mobile No" %>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <div class="picture_div">
            <%= image_tag @employee.picture.url(:medium), :class => "img-thumbnail employee_picture_img" %>
            <%= f.file_field :picture, :style => "display:none;" %>
            <div class="change_image_btn">
              Change Picture
              <span class="glyphicon glyphicon-edit"></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit :create, :value => (@employee.new_record? ? "Create":"Update"), :class => "btn btn-primary" %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Back", admin_employees_path %>
      </div>
    </div>
<% end %>

app/views/admin/employees/edit.html.erb
<div class="page-header">
  <h4>Edit Employee Record</h4>
</div>

<div class="row">
  <div class="col-lg-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/employees/index.html.erb
<div class="page-header">
  <h4>List of Employees</h4>
</div>

<div class="btn-toolbar">
  <%= link_to "New Employee", new_admin_employee_path, :class => "btn btn-primary pull-right" %>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>#</th>
    <th>Code</th>
    <th>Email</th>
    <th>Name</th>
    <th>Mobile</th>
    <th style="width: 160px;">Options</th>
  </tr>
  </thead>
  <tbody>
  <% @employees.each.with_index do |employee, i| %>
    <% _page = @page.to_i == 1 ? 0 : @page.to_i %>
    <tr>
      <td><%= _page+i+1 %></td>
      <td><%= employee.display_code %></td>
      <td><%= employee.email %></td>
      <td><%= employee.name %></td>
      <td><%= employee.contact_mobile %></td>
      <td>
        <%= link_to 'View', admin_employee_path(employee), :class => "btn btn-info btn-xs" %>
        <%= link_to 'Edit', edit_admin_employee_path(employee), :class => "btn btn-primary btn-xs" %>
        <%= link_to 'Delete', admin_employee_path(employee), :class => "btn btn-danger btn-xs", :method => :delete, :confirm => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
  </tbody>
  <% unless @employees %>
    <tfoot>
    <tr>
      <td colspan="5">
        No Records Found
      </td>
    </tr>
    </tfoot>
  <% end %>
</table>
<% if @employees %>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= will_paginate @employees, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
    </div>
  </div>
<% end %>

app/views/admin/employees/new.html.erb
<div class="page-header">
  <h4>New Employee Record</h4>
</div>


<div class="row">
  <div class="col-lg-9">
    <%= render "form" %>
  </div>
</div>

app/views/admin/employees/show.html.erb
<div class="page-header">
  <h4><%= "#{@employee.name}'s Profile"%></h4>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-2">
        <div class="employee_picture">
          <%= image_tag @employee.picture.url(:medium), :class => "img-thumbnail" %>
        </div>
      </div>
      <div class="col-lg-8">
        <h3 style="margin-top: 5px;">
          <%= @employee.full_name %>
          <small><%= @employee.designation.capitalize %></small>
        </h3>
        <table class="table" style="width: 70%">
          <tr>
            <td>Code</td>
            <td><%= @employee.display_code %></td>
          </tr>
          <tr>
            <td>Manager</td>
            <td>--</td>
          </tr>
          <tr>
            <td>Contact Mobile</td>
            <td><%= @employee.contact_mobile %></td>
          </tr>
          <tr>
            <td>Join Date</td>
            <td><%= @employee.join_date.strftime("%b %Y, %d") %></td>
          </tr>
          <tr>
            <td>Birth Date</td>
            <td><%= @employee.birth_date.strftime("%b %Y, %d") %></td>
          </tr>
          <tr>
            <td colspan="2">
              <%= link_to 'Edit', edit_admin_employee_path(@employee), :class => "btn btn-primary btn-xs" %>
              &nbsp;&nbsp;&nbsp;
              <%= link_to 'Back', admin_employees_path %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<script type="text/javascript">

  var idbSupported = false;
  var db;

  document.addEventListener("DOMContentLoaded", function(){

    if("indexedDB" in window) {
      idbSupported = true;
    }

    if(idbSupported) {
      var openRequest = indexedDB.open("test",1);

      openRequest.onupgradeneeded = function(e) {
        console.log("Upgrading...");
      }

      openRequest.onsuccess = function(e) {
        console.log("Success!");
        db = e.target.result;
      }

      openRequest.onerror = function(e) {
        console.log("Error");
        console.dir(e);
      }

    }

  },false);
</script>

app/views/home/index.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1>Leave Management</h1>
  <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It
    includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo03</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="header">

  </div>
  <!-- Static navbar -->
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <% if current_user.admin_user %>
                <li>
                  <%= link_to "Admin Panel", :class => "dropdown-toggle", "data-toggle" => "dropdown" do %>
                      Admin
                      <b class="caret"></b>
                  <% end %>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "Admin Users", admin_admin_users_path %>
                    </li>
                    <li>
                      <%= link_to "Employees", admin_employees_path %>
                    </li>
                  </ul>
                </li>
            <% end %>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
            </li>
        <% else %>
            <li>
              <%= link_to "Sign In", new_user_session_path %>
            </li>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>

  <%= yield %>

</div>
<!-- /container -->


</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>